### ISSUE TITLE
Unable to sign my Kotlin multiplatform library with Publication plugin

### ISSUE THREAD

**Issue by khalid64927** [icerockdev/moko-gradle-plugin#1]
I encountered an issue while attempting to sign my Kotlin Multiplatform library using the Publication Plugin. 
When running the ```./gradlew publish``` command, the following error occurred:

```
What went wrong:
Execution failed for task ':signAndroid-appPluginMarkerMavenPublication'.
> Cannot perform signing task ':signAndroid-appPluginMarkerMavenPublication' because it has no configured signatory
```

**Steps to Reproduce:**

1. Configure the publication plugin with the necessary signing environment variables (SIGNING_KEY_ID, SIGNING_PASSWORD, SIGNING_KEY).
2. Run the ```./gradlew publish``` command.

**Expected Behavior:**
The library should be published successfully with signing applied using the configured PGP keys.

**Observed Behavior:**
The publication process fails with the error mentioned above.

**Debugging Details:**
During my investigation, I encountered difficulties with the sign() function call within the PublishPlugin, which led to the failure. Although the specific reasons for the failure were not immediately apparent, through trial and error, modifying the sign() call as shown below resolved the issue:

```
if (signingKeyId != null) {
    useInMemoryPgpKeys(signingKeyId, signingKey, signingPassword)
    sign(configurations.archives.get()) // Updated this line
}
```

**Fix:**
By updating the sign() call to use configurations.archives.get() instead of publishing.publications, the publication process succeeded. While the exact cause of the failure remains unclear, this adjustment effectively resolved the issue.

**Comment by Alex009** [comment]
hi. this gradle plugin was developed for moko libraries, to simplify maintaining. glad to see that it useful for some another case too.
strange that on moko projects we not see this issue yet. 
can you give reproducer of this issue?
also, maybe you can sent PR with fix? or you still not sure that this change will completely fix issue?

**Comment by khalid64927** [comment]
Hi @Alex009 

I was working on publishing [this repo ](https://github.com/khalid64927/google-apple-pay). Thanks to you I didn't had to bootstrap everything from scratch. I was facing this issue while publishing with publish workflow, you can see the [workflow run logs here](https://github.com/khalid64927/google-apple-pay/actions/runs/8672701397/job/23783296242) or try on moko-permission, I am able to reproduce it on master branch of moko-permission.

[moko-permissions build-logs.log](https://github.com/icerockdev/moko-gradle-plugin/files/14971393/moko-permissions.build-logs.log)

I'll be glad to open the PR just that i'm bit unsure if its happening just to me due to some local setup. That change worked for me though.
